USE master;
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Some3xtr4Passw00rd';
GO

CREATE CERTIFICATE CryptoBackup WITH SUBJECT = 'My BackUp Certificate';
GO

DROP CERTIFICATE CryptoBackup
GO
DROP MASTER KEY
GO